# Generated by Django 5.0.7 on 2024-09-06 20:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Beneficiarios',
            fields=[
                ('id_beneficiario', models.AutoField(primary_key=True, serialize=False)),
                ('rut', models.CharField(max_length=50)),
                ('dv', models.CharField(max_length=10)),
                ('nombres', models.CharField(max_length=255)),
                ('primer_apellido', models.CharField(max_length=100)),
                ('segundo_apellido', models.CharField(blank=True, max_length=100)),
                ('comuna', models.CharField(max_length=100)),
                ('provincia', models.CharField(max_length=100)),
                ('codigo_proyecto', models.IntegerField(blank=True)),
                ('nombre_grupo', models.CharField(blank=True, max_length=255)),
                ('sexo', models.CharField(blank=True, max_length=10)),
            ],
            options={
                'db_table': 'beneficiarios',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Decretos',
            fields=[
                ('id_decreto', models.AutoField(primary_key=True, serialize=False)),
                ('decreto', models.CharField(max_length=10)),
                ('tipologia', models.CharField(max_length=50)),
                ('tramo', models.IntegerField(blank=True, null=True)),
                ('decreto_id_beneficiario', models.ForeignKey(db_column='decreto_id_beneficiario', on_delete=django.db.models.deletion.CASCADE, to='serviuapp.beneficiarios')),
            ],
            options={
                'db_table': 'decretos',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Resoluciones',
            fields=[
                ('id_resolucion', models.AutoField(primary_key=True, serialize=False)),
                ('resolucion', models.IntegerField()),
                ('fecha_resolucion', models.DateField()),
                ('seleccion', models.CharField(max_length=50)),
                ('ano_imputacion_res_of', models.IntegerField()),
                ('resolucion_id_beneficiario', models.ForeignKey(db_column='resolucion_id_beneficiario', on_delete=django.db.models.deletion.CASCADE, to='serviuapp.beneficiarios')),
            ],
            options={
                'db_table': 'resoluciones',
                'managed': True,
            },
        ),
    ]
