# Generated by Django 5.0.7 on 2025-08-16 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('serviuapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='beneficiarios',
            name='codigo_proyecto',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='decretos',
            name='tipologia',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='resoluciones',
            name='ano_imputacion_res_of',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='resoluciones',
            name='fecha_resolucion',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='resoluciones',
            name='resolucion',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='resoluciones',
            name='seleccion',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
