# Generated by Django 5.0.7 on 2025-08-17 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('serviuapp', '0002_alter_beneficiarios_codigo_proyecto_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChatInteraction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.CharField(help_text='ID único de sesión', max_length=100)),
                ('user_question', models.TextField(help_text='Pregunta del usuario')),
                ('ai_response', models.TextField(help_text='Respuesta de la IA')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('user_rut', models.CharField(blank=True, max_length=50, null=True)),
                ('user_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('satisfaction_rating', models.IntegerField(blank=True, choices=[(1, '1 - Muy insatisfecho'), (2, '2 - Insatisfecho'), (3, '3 - Neutral'), (4, '4 - Satisfecho'), (5, '5 - Muy satisfecho')], null=True)),
                ('question_category', models.CharField(blank=True, help_text='Categoría automática de la pregunta', max_length=100, null=True)),
                ('sentiment_score', models.FloatField(blank=True, help_text='Puntuación de sentimiento (-1 a 1)', null=True)),
                ('response_time_ms', models.IntegerField(blank=True, help_text='Tiempo de respuesta en milisegundos', null=True)),
                ('was_helpful', models.BooleanField(blank=True, null=True)),
                ('feedback_text', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'chat_interactions',
                'ordering': ['-timestamp'],
                'managed': True,
            },
        ),
    ]
