"""
Django settings for serviu project.

Generated by 'django-admin startproject' using Django 4.2.4.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""
import logging
import os
from django.conf import settings
from pathlib import Path
import os
import pymysql
from import_export.formats.base_formats import CSV, XLSX
import datetime
from dotenv import load_dotenv

load_dotenv()

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-n2x10c7hb-5_rs5ot3g7!jr-77+t6b+ej4-&*17w@$ur6atd(='

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = [
    "maverixti.cl",
    "www.maverixti.cl",
]
# Application definition

INSTALLED_APPS = [
    'whitenoise.runserver_nostatic',
    # 'material',
    # 'material.admin',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'import_export',
    'serviuapp'
]

IMPORT_EXPORT_USE_TRANSACTIONS = True
IMPORT_FORMATS = [CSV, XLSX]
CSRF_TRUSTED_ORIGINS = [
    "https://maverixti.cl",
    "https://www.maverixti.cl",
]
CSRF_COOKIE_PATH = "/"
SESSION_COOKIE_PATH = "/"
CSRF_COOKIE_SECURE = True
SESSION_COOKIE_SECURE = True
CSRF_COOKIE_SAMESITE = 'None'
SESSION_COOKIE_SAMESITE = 'None'

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'serviu.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'templates')],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'wsgi.application'


# Database
# https://docs.djangoproject.com/en/4.2/ref/settings/#databases

pymysql.install_as_MySQLdb()

DATABASES = {
    'default': {
        # 'ENGINE': 'django.db.backends.mysql',
        # 'NAME': 'serviuapp',
        # 'USER': 'root',
        # 'PASSWORD': '',
        # 'HOST': 'localhost',
        # 'PORT': '3306'

        'ENGINE': 'django.db.backends.mysql',
        'NAME': 'maverixt_serviuapp',
        'USER': 'maverixt_serviuapp',
        'PASSWORD': 'Sabanamala25!',
        'HOST': 'localhost',
        'PORT': '3306'
    }
    
}

# Password validation
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.2/topics/i18n/


LANGUAGE_CODE = 'es'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.2/howto/static-files/

# Static files 
STATIC_URL = '/serviuapp/static/' 
STATIC_ROOT = '/home/maverixt/public_html/serviuapp/static/'
 # Si tienes una carpeta "static" dentro del proyecto (para CSS/js propios) 
STATICFILES_DIRS = [ BASE_DIR / 'static', ]







SECURE_CROSS_ORIGIN_OPENER_POLICY = None



# Default primary key field type
# https://docs.djangoproject.com/en/4.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
# BASE_DIR ya debe estar definido en tu archivo settings.py

LOG_DIR = os.path.join(BASE_DIR, 'logs')

# Definir el archivo de logs que quieres usar
LOG_FILENAME = 'app.log'

if not os.path.exists(LOG_DIR):
    os.makedirs(LOG_DIR)
LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'handlers': {
        'console': {
            'class': 'logging.StreamHandler',
        },
    },
    'root': {
        'handlers': ['console'],
        'level': 'INFO',
    },
    'loggers': {
        'serviuapp.views': {
            'handlers': ['console'],
            'level': 'INFO',
            'propagate': False,
        },
    },
}
WSGI_APPLICATION = os.environ.get('WSGI_APPLICATION', 'serviu.wsgi')

# Login settings
LOGIN_URL = '/accounts/login/'
LOGIN_REDIRECT_URL = '/'  # ← Ya está configurado correctamente para redirigir al dashboard

# OpenAI Configuration
OPENAI_API_KEY = os.getenv('OPENAI_API_KEY')

# DeepSeek API Configuration
DEEPSEEK_API_KEY = os.getenv('DEEPSEEK_API_KEY')

# Ollama Configuration
OLLAMA_URL = 'http://localhost:11434'  # URL por defecto de Ollama
OLLAMA_MODEL = 'mistral'  # Tu modelo Mistral
